import type { Metadata } from "next";
import { DM_Sans, Inter } from "next/font/google";
import "./globals.css";

const raleway = Inter({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-raleway",
  subsets: ["latin"],
});

const dm_sans = DM_Sans({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${dm_sans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
